v2.2.0 / v2.0.20

diff --git a/.github/workflows/ci-alpine-build.yml b/.github/workflows/ci-alpine-build.yml
--- a/.github/workflows/ci-alpine-build.yml
+++ b/.github/workflows/ci-alpine-build.yml
@@ -1,4 +1,3 @@
-# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
 name: ci - alpine build
 
 on:
@@ -24,31 +23,37 @@ on:
         description: "script name"
         required: true
         type: string
+
 jobs:
-  build-alpine:
-    runs-on: ubuntu-24.04-arm
+  build:
+    runs-on: ${{ matrix.runs_on }}
     strategy:
       fail-fast: false
       matrix:
+        runs_on: ["ubuntu-24.04-arm"]
         os_id: [alpine]
         os_version_id: [edge]
         qbt_cross_name: ["armhf", "armv7", "aarch64", "riscv64", "x86_64", "x86"]
         qbt_libtorrent_version: ["1.2", "2.0"]
-        qbt_build_tool: ["", "qmake"]
+        qbt_build_tool: [""]
+        qbt_qbittorrent_tag: [""]
         include:
-          - qbt_build_tool: "qmake"
-            qbt_qt_version_name: "qt5-"
-            qbt_qt_version: "5"
           - qbt_build_tool: ""
             qbt_qt_version_name: ""
-            qbt_qt_version: "6"
 
     name: "${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}libtorrent-v${{ matrix.qbt_libtorrent_version }}"
 
     env:
       qbt_build_dir: "qbt-build"
-      script_name: ${{ inputs.script_name }}
       container_name: "multiarch"
+      script_name: ${{ inputs.script_name }}
+      set_skip_icu: ${{ inputs.icu }}
+      set_workflow_files: ${{ inputs.workflow-files }}
+      set_build_debug: ${{ inputs.debug }}
+      set_qbt_mcm_url: "" # default is userdocs/qbt-musl-cross-make
+      set_qbt_with_qemu: "" # default is yes
+      set_qbt_host_deps: "" # default is no
+      set_qbt_host_deps_repo: "" # default is userdocs/qbt-host-deps
 
     steps:
       - name: Checkout ${{ inputs.distinct_id }}
@@ -56,152 +61,126 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: Host - Create Docker template env file ${{ inputs.distinct_id }}
-        env:
-          set_skip_icu: ${{ inputs.icu }}
-          set_workflow_files: ${{ inputs.workflow-files }}
-          set_build_debug: ${{ inputs.debug }}
+      - name: Download ${{ env.script_name }}
         run: |
-          printf '%s\n' "qbt_build_dir=${{ env.qbt_build_dir }}" > env.custom
-          printf '%s\n' "qbt_libtorrent_version=${{ matrix.qbt_libtorrent_version }}" >> env.custom
-          printf '%s\n' "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
-          printf '%s\n' "qbt_build_tool=${{ matrix.qbt_build_tool }}" >> env.custom
-          printf '%s\n' "qbt_cross_name=${{ matrix.qbt_cross_name }}" >> env.custom
-          printf '%s\n' "qbt_patches_url=${{ github.repository }}" >> env.custom
+          # Make sure the branch is set to master for qbittorrent-nox-static and main qbittorrent-nox-static-test
+          if [[ ! -f "${script_name}" ]]; then
+            echo "Downloading ${script_name} from userdocs/qbittorrent-nox-static"
+            curl -LO "https://raw.githubusercontent.com/userdocs/qbittorrent-nox-static/refs/heads/master/${script_name}"
+            chmod +x "${script_name}"
+          fi
+
+      - name: Host - Create Docker template env file ${{ inputs.distinct_id }}
+        run: |
+          printf '%s\n' "qbt_revision_url=${{ github.repository }}" > env.custom
+          printf '%s\n' "qbt_zlib_type=zlib" >> env.custom
           printf '%s\n' "qbt_skip_icu=${set_skip_icu}" >> env.custom
           printf '%s\n' "qbt_boost_tag=${{ matrix.qbt_boost_tag }}" >> env.custom
+          printf '%s\n' "qbt_libtorrent_version=${{ matrix.qbt_libtorrent_version }}" >> env.custom
           printf '%s\n' "qbt_libtorrent_tag=${{ matrix.qbt_libtorrent_tag }}" >> env.custom
+          printf '%s\n' "qbt_libtorrent_master_jamfile=" >> env.custom
+          printf '%s\n' "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
           printf '%s\n' "qbt_qt_tag=${{ matrix.qbt_qt_tag }}" >> env.custom
           printf '%s\n' "qbt_qbittorrent_tag=${{ matrix.qbt_qbittorrent_tag }}" >> env.custom
-          printf '%s\n' "qbt_libtorrent_master_jamfile=" >> env.custom
+          printf '%s\n' "qbt_build_dir=${qbt_build_dir}" >> env.custom
+          printf '%s\n' "qbt_build_tool=${{ matrix.qbt_build_tool }}" >> env.custom
+          printf '%s\n' "qbt_cross_name=${{ matrix.qbt_cross_name }}" >> env.custom
+          printf '%s\n' "qbt_mcm_url=${set_qbt_mcm_url}" >> env.custom
+          printf '%s\n' "qbt_patches_url=${{ github.repository }}" >> env.custom
           printf '%s\n' "qbt_workflow_files=${set_workflow_files}" >> env.custom
-          printf '%s\n' "qbt_workflow_artifacts=" >> env.custom
           printf '%s\n' "qbt_cache_dir=" >> env.custom
           printf '%s\n' "qbt_optimise_strip=" >> env.custom
           printf '%s\n' "qbt_build_debug=${set_build_debug}" >> env.custom
-          printf '%s\n' "qbt_revision_url=${{ github.repository }}" >> env.custom
           printf '%s\n' "qbt_standard=" >> env.custom
           printf '%s\n' "qbt_static_ish=" >> env.custom
+          printf '%s\n' "qbt_optimise=${qbt_optimise}" >> env.custom
+          printf '%s\n' "qbt_with_qemu=${set_qbt_with_qemu}" >> env.custom
+          printf '%s\n' "qbt_host_deps=${set_qbt_host_deps}" >> env.custom
+          printf '%s\n\n' "qbt_host_deps_repo=${set_qbt_host_deps_repo}" >> env.custom
 
-      # - name: Host - Github env to container ${{ inputs.distinct_id }}
-      #   run: env >> env.custom
-
-      - name: Host - check stuff ${{ inputs.distinct_id }}
-        run: export $(cat env.custom) && bash ${script_name}
-
-      - name: Host - qBittorrent v5 transition ${{ inputs.distinct_id }}
+      - name: Host - Debian based specific env ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
         run: |
-          if [[ -f "${qbt_build_dir}/release_info/disable-qt5" || -f "disable-qt5" ]]; then
-              printf '%s\n' "disable_qt5=yes" >> $GITHUB_ENV
-              printf '%s\n' "Found file: \`disable-qt5\` -> setting env: \`disable_qt5=yes\`" >> $GITHUB_STEP_SUMMARY
-          fi
+          printf '%s\n' "LANG=C.UTF-8" >> env.custom
+          printf '%s\n' "LC_ALL=C.UTF-8" >> env.custom
+          printf '%s\n\n' "DEBIAN_FRONTEND=noninteractive" >> env.custom
 
-      - name: Host - phased updates ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: printf '%s\n' 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
+      - name: Host - Bootstrap qemu
+        uses: userdocs/actions/qemu@main
 
-      - name: Host - update ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: sudo apt-get update
-
-      # - name: Host - upgrade ${{ inputs.distinct_id }}
-      #   run: sudo apt-get -y upgrade
-
-      - name: Host - set up qemu-user-static binfmt-support ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: sudo apt install libpipeline1 qemu-user-static binfmt-support
-
-      - name: Host - Create docker ${{ env.multiarch }} container ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: |
-          # We create an Alpine edge container for cross-compilation with a user named gh which has same id as runner 1001 and provide sudo access
-          # This way we can run commands as a non-root user, avoiding permission issues on host runner. Switching between user and root as needed.
-          docker run --name ${container_name} -it -d --env-file env.custom -w /home/gh -v ${{ github.workspace }}:/home/gh ${{ matrix.os_id }}:${{ matrix.os_version_id }}
-          # Create the user gh with the id 1001:1001 which is the same as the runner user id and group id.
-          docker exec ${container_name} sh -c 'adduser -h /home/gh -Ds /bin/bash -u 1001 gh && apk add sudo'
-          # Allow the user gh to run sudo without password prompt: docker exec -u gh:gh ${container_name} sudo ls
-          docker exec ${container_name} sh -c 'printf "%s" "gh ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/gh'
+      - uses: userdocs/actions/qbt_docker@main
+        with:
+            # if the env.custom file exists, it will be used to pass environment
+            distinct_id: ${{ inputs.distinct_id }}
+            use_host_env: "false"
+            container_name: ${{ env.container_name }}
+            os_id: ${{ matrix.os_id }}
+            os_version_id: ${{ matrix.os_version_id }}
+            custom_docker_commands: ""
+            additional_alpine_apps: "bash curl git"
+            additional_debian_apps: "bash curl git"
 
       - name: Host - patches ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: mkdir -p ${qbt_build_dir}/patches && cp -r patches/* ${qbt_build_dir}/patches/
+        if: hashFiles('patches/**') != ''
+        run: mkdir -p ${qbt_build_dir}/patches && cp -rf patches/* ${qbt_build_dir}/patches/
 
-      - name: Docker - apk update ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec ${container_name} apk update
-
-      - name: Docker - apk install bash ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec ${container_name} apk add bash
-
-      - name: Docker - Bootstrap test tools ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec ${container_name} bash ${script_name} update install_test
-
-      - name: Docker - Bootstrap core deps ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec ${container_name} bash ${script_name} install_core
+      - name: Docker - bootstrap_deps ${{ inputs.distinct_id }}
+        if: inputs.script_name == 'qbt-nox-static.bash'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} bootstrap_deps
 
       - name: Docker - Bootstrap build ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} -bs-a
 
-      - name: Docker - zlib-ng ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
+      - name: Docker - glibc ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} glibc
+
+      - name: Docker - zlib ${{ inputs.distinct_id }}
         run: docker exec -u gh:gh ${container_name} bash ${script_name} zlib
 
       - name: Docker - iconv ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
+        if: matrix.qbt_libtorrent_version == '1.2'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} iconv
 
       - name: Docker - icu ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
+        if: env.set_skip_icu == 'no'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} icu
 
       - name: Docker - openssl ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} openssl
 
       - name: Docker - boost ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} boost
 
       - name: Docker - libtorrent ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} libtorrent
 
       - name: Docker - double_conversion ${{ inputs.distinct_id }}
-        if: matrix.qbt_build_tool == '' && env.disable_qt5 != 'yes'
+        if: matrix.qbt_build_tool == ''
         run: docker exec -u gh:gh ${container_name} bash ${script_name} double_conversion
 
       - name: Docker - qtbase ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} qtbase
 
       - name: Docker - qttools ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} qttools
 
       - name: Docker - qbittorrent ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         run: docker exec -u gh:gh ${container_name} bash ${script_name} qbittorrent
 
       - name: Docker - Set release asset name ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec -u gh:gh -w /home/gh/${{ env.qbt_build_dir }}/completed ${container_name} mv -f qbittorrent-nox ${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
+        run: docker exec -u gh:gh -w /home/gh/${qbt_build_dir}/completed ${container_name} mv -f qbittorrent-nox ${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
 
       - name: Generate artifact attestation  ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
         uses: actions/attest-build-provenance@v2
         with:
           subject-path: "${{ env.qbt_build_dir }}/completed/${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox"
 
       - name: Docker - Release Info ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: docker exec -u gh:gh -w /home/gh/${{ env.qbt_build_dir }}/release_info ${container_name} bash -c 'mv *.md *.json '/home/gh/${{ env.qbt_build_dir }}/completed''
+        run: docker exec -u gh:gh -w /home/gh/${qbt_build_dir}/release_info ${container_name} bash -c 'mv *.md *.json '/home/gh/${qbt_build_dir}/completed''
 
       - name: Host - Upload libtorrent-v${{ matrix.qbt_libtorrent_version }}-qbittorrent-nox and release info artifact ${{ inputs.distinct_id }}
-        if: success() && env.disable_qt5 != 'yes'
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: libtorrent-v${{ matrix.qbt_libtorrent_version }}-${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
@@ -210,15 +189,15 @@ jobs:
             !${{ env.qbt_build_dir }}/completed/*.png
 
       - name: Host - Upload cmake graphs artifact ${{ inputs.distinct_id }}
-        if: success() && matrix.qbt_build_tool == '' && env.disable_qt5 != 'yes'
+        if: success() && matrix.qbt_build_tool == ''
         uses: actions/upload-artifact@v4
         with:
           name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-graphs"
           path: "${{ env.qbt_build_dir }}/completed/*.png"
 
-      - name: Host - Upload logs on error
-        if: failure() && env.disable_qt5 != 'yes'
-        uses: actions/upload-artifact@v4
-        with:
-          name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-logs"
-          path: "${{ env.qbt_build_dir }}/logs/*"
+      # - name: Host - Upload build dir on error or cancel
+      #   if: ( cancelled() || failure() )
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-logs"
+      #     path: "${{ env.qbt_build_dir }}"
diff --git a/.github/workflows/ci-debian-build.yml b/.github/workflows/ci-debian-build.yml
--- a/.github/workflows/ci-debian-build.yml
+++ b/.github/workflows/ci-debian-build.yml
@@ -26,150 +26,183 @@ on:
 
 jobs:
   build:
-    defaults:
-      run:
-        shell: bash
     runs-on: ${{ matrix.runs_on }}
     strategy:
       fail-fast: false
       matrix:
-        runs_on: [ubuntu-24.04, ubuntu-24.04-arm]
-        container_id: [debian, ubuntu]
-        container_codename: [bookworm, noble]
-        qbt_build_tool: ["cmake", "qmake"]
+        runs_on: ["ubuntu-24.04", "ubuntu-24.04-arm"]
+        os_id: ["debian", "ubuntu"]
+        os_version_id: ["bookworm", "noble"]
+        qbt_cross_name: ["default", "aarch64", "x86_64", "riscv64"]
         qbt_libtorrent_version: ["1.2", "2.0"]
+        qbt_build_tool: [""]
+        qbt_qt_version: ["6"]
         exclude:
-          - container_id: debian
-            container_codename: noble
-          - container_id: ubuntu
-            container_codename: bookworm
+          - os_id: "debian"
+            qbt_cross_name: "riscv64"
+          - os_id: "debian"
+            os_version_id: "noble"
+          - os_id: "ubuntu"
+            os_version_id: "bookworm"
+          - runs_on: "ubuntu-24.04"
+            qbt_cross_name: "x86_64"
+          - runs_on: "ubuntu-24.04-arm"
+            qbt_cross_name: "aarch64"
         include:
-          - qbt_build_tool: "qmake"
-            qbt_qt_version: "5"
-          - qbt_build_tool: "cmake"
-            qbt_qt_version: "6"
-          - runs_on: ubuntu-24.04
-            docker_arch: "amd64"
-          - runs_on: ubuntu-24.04-arm
-            docker_arch: "arm64v8"
+          - runs_on: "ubuntu-24.04"
+            host_name: "x86_64"
+          - runs_on: "ubuntu-24.04-arm"
+            host_name: "aarch64"
+          - qbt_build_tool: ""
+            qbt_qt_version_name: ""
 
-    name: "${{ matrix.docker_arch }}-${{ matrix.container_id }}-${{ matrix.container_codename }}-${{ matrix.qbt_libtorrent_version }}-qt-${{ matrix.qbt_qt_version }}-${{ matrix.qbt_build_tool }}"
+    name: "${{ matrix.host_name}}-${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}libtorrent-v${{ matrix.qbt_libtorrent_version }}"
 
-    env: # host
+    env:
       qbt_build_dir: "qbt-build"
-      disable_qt5: ""
-      artifact_name: "${{ matrix.docker_arch }}-${{ matrix.container_id }}-${{ matrix.container_codename }}-${{ matrix.qbt_libtorrent_version }}-qt-${{ matrix.qbt_qt_version }}-${{ matrix.qbt_build_tool }}-nox"
+      container_name: "multiarch"
       script_name: ${{ inputs.script_name }}
+      set_skip_icu: ${{ inputs.icu }}
+      set_workflow_files: ${{ inputs.workflow-files }}
+      set_build_debug: ${{ inputs.debug }}
+      set_qbt_mcm_url: "" # default is userdocs/qbt-musl-cross-make
+      set_qbt_with_qemu: "" # default is yes
+      set_qbt_host_deps: "" # default is no
+      set_qbt_host_deps_repo: "" # default is userdocs/qbt-host-deps
 
-    container:
-      image: ${{ matrix.docker_arch }}/${{ matrix.container_id }}:${{ matrix.container_codename }}
-      env: # container
-        LANG: C.UTF-8
-        LC_ALL: C.UTF-8
-        DEBIAN_FRONTEND: noninteractive
-        disable_qt5: ${{ env.disable_qt5 }}
-        qbt_build_dir: ${{ env.qbt_build_dir }}
-        qbt_libtorrent_version: ${{ matrix.qbt_libtorrent_version }}
-        qbt_qt_version: ${{ matrix.qbt_qt_version }}
-        qbt_build_tool: ${{ matrix.qbt_build_tool }}
-        qbt_cross_name: ${{ matrix.qbt_cross_name }}
-        qbt_patches_url: ${{ github.repository }}
-        qbt_skip_icu: ${{ inputs.icu }}
-        qbt_boost_tag: ${{ matrix.qbt_boost_tag }}
-        qbt_libtorrent_tag: ${{ matrix.qbt_libtorrent_tag }}
-        qbt_qt_tag: ${{ matrix.qbt_qt_tag }}
-        qbt_qbittorrent_tag: ${{ matrix.qbt_qbittorrent_tag }}
-        qbt_libtorrent_master_jamfile: ""
-        qbt_workflow_files: ${{ inputs.workflow-files }}
-        qbt_workflow_artifacts: ""
-        qbt_cache_dir: ""
-        qbt_optimise_strip: ""
-        qbt_build_debug: ${{ inputs.debug }}
-        qbt_revision_url: ${{ github.repository }}
-        qbt_standard: ""
-        qbt_static_ish: ""
     steps:
       - name: Checkout ${{ inputs.distinct_id }}
         uses: actions/checkout@v4
         with:
           persist-credentials: false
 
-      - name: bootstrap patches ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
+      - name: Host - Create Docker template env file ${{ inputs.distinct_id }}
+        run: |
+          printf '%s\n' "qbt_revision_url=${{ github.repository }}" > env.custom
+          printf '%s\n' "qbt_zlib_type=zlib" >> env.custom
+          printf '%s\n' "qbt_skip_icu=${set_skip_icu}" >> env.custom
+          printf '%s\n' "qbt_boost_tag=${{ matrix.qbt_boost_tag }}" >> env.custom
+          printf '%s\n' "qbt_libtorrent_version=${{ matrix.qbt_libtorrent_version }}" >> env.custom
+          printf '%s\n' "qbt_libtorrent_tag=${{ matrix.qbt_libtorrent_tag }}" >> env.custom
+          printf '%s\n' "qbt_libtorrent_master_jamfile=" >> env.custom
+          printf '%s\n' "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
+          printf '%s\n' "qbt_qt_tag=${{ matrix.qbt_qt_tag }}" >> env.custom
+          printf '%s\n' "qbt_qbittorrent_tag=${{ matrix.qbt_qbittorrent_tag }}" >> env.custom
+          printf '%s\n' "qbt_build_dir=${{ env.qbt_build_dir }}" >> env.custom
+          printf '%s\n' "qbt_build_tool=${{ matrix.qbt_build_tool }}" >> env.custom
+          printf '%s\n' "qbt_cross_name=${{ matrix.qbt_cross_name }}" >> env.custom
+          printf '%s\n' "qbt_mcm_url=${set_qbt_mcm_url}" >> env.custom
+          printf '%s\n' "qbt_patches_url=${{ github.repository }}" >> env.custom
+          printf '%s\n' "qbt_workflow_files=${set_workflow_files}" >> env.custom
+          printf '%s\n' "qbt_cache_dir=" >> env.custom
+          printf '%s\n' "qbt_optimise_strip=" >> env.custom
+          printf '%s\n' "qbt_build_debug=${set_build_debug}" >> env.custom
+          printf '%s\n' "qbt_standard=" >> env.custom
+          printf '%s\n' "qbt_static_ish=" >> env.custom
+          printf '%s\n' "qbt_optimise=${qbt_optimise}" >> env.custom
+          printf '%s\n' "qbt_with_qemu=${set_qbt_with_qemu}" >> env.custom
+          printf '%s\n' "qbt_host_deps=${set_qbt_host_deps}" >> env.custom
+          printf '%s\n\n' "qbt_host_deps_repo=${set_qbt_host_deps_repo}" >> env.custom
+
+      - name: Host - Debian based specific env ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
+        run: |
+          printf '%s\n' "LANG=C.UTF-8" >> env.custom
+          printf '%s\n' "LC_ALL=C.UTF-8" >> env.custom
+          printf '%s\n\n' "DEBIAN_FRONTEND=noninteractive" >> env.custom
+
+      - name: Host - Bootstrap qemu
+        uses: userdocs/actions/qemu@main
+
+      - uses: userdocs/actions/qbt_docker@main
+        with:
+            # if the env.custom file exists, it will be used to pass environment
+            distinct_id: ${{ inputs.distinct_id }}
+            use_host_env: "false"
+            container_name: ${{ env.container_name }}
+            os_id: ${{ matrix.os_id }}
+            os_version_id: ${{ matrix.os_version_id }}
+            custom_docker_commands: ""
+            additional_alpine_apps: "bash curl git"
+            additional_debian_apps: "bash curl git"
+
+      - name: Host - patches ${{ inputs.distinct_id }}
         run: mkdir -p ${qbt_build_dir}/patches && cp -r patches/* ${qbt_build_dir}/patches/
 
-      - name: Bootstrap test tools ${{ inputs.distinct_id }}
-        run: bash ${script_name} update install_test
+      - name: Docker - bootstrap_deps ${{ inputs.distinct_id }}
+        if: inputs.script_name == 'qbt-nox-static.bash'
+        run: docker exec ${container_name} bash ${script_name} bootstrap_deps
 
-      - name: qBittorrent v5 transition ${{ inputs.distinct_id }}
-        run: |
-          if [[ -f "${qbt_build_dir}/release_info/disable-qt5" || -f "disable-qt5" ]]; then
-              printf '%s\n' "disable_qt5=yes" >> $GITHUB_ENV
-              printf '%s\n' "Found file: \`disable-qt5\` -> setting env: \`disable_qt5=yes\`" >> $GITHUB_STEP_SUMMARY
-          fi
+      - name: Docker - Bootstrap build ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} -bs-a
 
-      - name: Bootstrap core deps ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} install_core
+      - name: Docker - glibc ${{ inputs.distinct_id }}
+        if : matrix.os_id != 'alpine'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} glibc
 
-      - name: Bootstrap build ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} -bs-a
+      - name: Docker - zlib ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} zlib
 
-      - name: glibc ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} glibc
+      - name: Docker - iconv ${{ inputs.distinct_id }}
+        if: matrix.qbt_libtorrent_version == '1.2'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} iconv
 
-      - name: zlib ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} zlib
+      - name: Docker - icu ${{ inputs.distinct_id }}
+        if: env.set_skip_icu == 'no'
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} icu
 
-      - name: iconv ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} iconv
+      - name: Docker - openssl ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} openssl
 
-      - name: icu ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} icu
+      - name: Docker - boost ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} boost
 
-      - name: openssl ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} openssl
+      - name: Docker - libtorrent ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} libtorrent
 
-      - name: boost ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} boost
+      - name: Docker - double_conversion ${{ inputs.distinct_id }}
+        if: matrix.qbt_build_tool == ''
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} double_conversion
 
-      - name: libtorrent ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} libtorrent
+      - name: Docker - qtbase ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} qtbase
 
-      - name: double conversion ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes' && matrix.qbt_build_tool == 'cmake'
-        run: bash ${script_name} double_conversion
+      - name: Docker - qttools ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} qttools
 
-      - name: qtbase ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} qtbase
+      - name: Docker - qbittorrent ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh ${container_name} bash ${script_name} qbittorrent
 
-      - name: qttools ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} qttools
+      - name: Docker - Set release asset name ${{ inputs.distinct_id }}
+        run: docker exec -u gh:gh -w /home/gh/${{ env.qbt_build_dir }}/completed ${container_name} mv -f qbittorrent-nox ${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
 
-      - name: qbittorrent ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        run: bash ${script_name} qbittorrent
+      # - name: Generate artifact attestation  ${{ inputs.distinct_id }}
+      #   uses: actions/attest-build-provenance@v2
+      #   with:
+      #     subject-path: "${{ env.qbt_build_dir }}/completed/${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox"
 
-      - name: Upload ${{ env.artifact_name }} artifacts ${{ inputs.distinct_id }}
-        if: env.disable_qt5 != 'yes'
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.artifact_name }}
-          path: ${{ env.qbt_build_dir }}/completed/qbittorrent-nox
+      # - name: Docker - Release Info ${{ inputs.distinct_id }}
+      #   run: docker exec -u gh:gh -w /home/gh/${{ env.qbt_build_dir }}/release_info ${container_name} bash -c 'mv *.md *.json '/home/gh/${{ env.qbt_build_dir }}/completed''
 
-      - name: Host - Upload logs on error
-        if: failure() && env.disable_qt5 != 'yes'
-        uses: actions/upload-artifact@v4
-        with:
-          name: "${{ env.artifact_name }}-logs"
-          path: "${{ env.qbt_build_dir }}"
+      # - name: Host - Upload libtorrent-v${{ matrix.qbt_libtorrent_version }}-qbittorrent-nox and release info artifact ${{ inputs.distinct_id }}
+      #   if: success()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: libtorrent-v${{ matrix.qbt_libtorrent_version }}-${{ matrix.qbt_cross_name }}-${{ matrix.qbt_qt_version_name }}qbittorrent-nox
+      #     path: |
+      #       ${{ env.qbt_build_dir }}/completed/*
+      #       !${{ env.qbt_build_dir }}/completed/*.png
+
+      # - name: Host - Upload cmake graphs artifact ${{ inputs.distinct_id }}
+      #   if: success() && matrix.qbt_build_tool == ''
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-graphs"
+      #     path: "${{ env.qbt_build_dir }}/completed/*.png"
+
+      # - name: Host - Upload build dir on error or cancel
+      #   if: ( cancelled() || failure() )
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: "${{ matrix.qbt_cross_name }}-libtorrent-v${{ matrix.qbt_libtorrent_version }}-logs"
+      #     path: "${{ env.qbt_build_dir }}"
